name: Build

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        arch: [arm64, amd64, 386]
        go-version: ["1.20"]
        exclude:
          - os: macOS-latest
            arch: 386
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Build Go ${{ matrix.go-version }} ${{ matrix. os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: GOARCH=${{ matrix.arch }} go build -o build/bizip_${{ matrix.os }}_${{ matrix.arch }} -v ./...

      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build

  calculate_checksums:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: build

      - name: Calculate Checksums
        run: |
          mkdir checksums
          cd build
          md5sum * > ../checksums/md5_checksums.txt
          sha1sum * > ../checksums/sha1_checksums.txt
          sha256sum * > ../checksums/sha256_checksums.txt

      - name: Upload Checksums
        uses: actions/upload-artifact@v3
        with:
          name: checksums
          path: checksums
