name: Build

on:
  push:
    branches: [ "main" ]
    tags: "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os: [darwin, linux, windows]
        arch: [386, amd64, arm64]
        exclude:
          - os: darwin
            arch: 386
          - os: linux
            arch: arm64
          - os: windows
            arch: arm64
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o build/bizip_${{ matrix.os }}_${{ matrix.arch }} ./...
        
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: build

  calculate_checksums:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      
    - uses: actions/download-artifact@v3
      with:
          name: binaries
          path: build
      
    - name: Calculate Checksums
      run: |
        mkdir checksums
        md5sum build/* > checksums/md5_checksums.txt
        sha1sum build/* > checksums/sha1_checksums.txt
        sha256sum build/* > checksums/sha256_checksums.txt
    
    - uses: actions/upload-artifact@v3
      with:
        name: checksums
        path: checksums