name: Build

on:
  push:
    tags: '*'
    
jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: Build Linux amd64 Binary
      run: env GOOS=linux GOARCH=amd64 go build -v -o build/bizip_linux_amd64 ./...

    - name: Build Linux arm64 Binary
      run: env GOOS=linux GOARCH=arm64 go build -v -o build/bizip_linux_arm64 ./...
  
    - name: Build Darwin amd64 Binary
      run: env GOOS=darwin GOARCH=amd64 go build -v -o build/bizip_darwin_amd64 ./...
      
    - name: Build Darwin arm64 Binary
      run: env GOOS=darwin GOARCH=arm64 go build -v -o build/bizip_darwin_arm64 ./...
      
    - name: Build Windows amd64 Binary
      run: env GOOS=windows GOARCH=amd64 go build -v -o build/bizip_windows_amd64.exe ./...

    - uses: actions/upload-artifact@v3
      with:
        name: bizip
        path: build/
